'use client';

import { useState, useRef } from 'react';
import { Calendar, LayoutGrid, Plus, Share2, Copy, Check, FileDown } from 'lucide-react';
import Link from 'next/link';
import { TimelineView } from './timeline-view';
import { UnifiedTimeline, type TimelineTask, type TimelineVendorBooking, type TimelineEvent as UnifiedTimelineEvent } from './unified-timeline';
import type { WeddingEventData } from '@/lib/wedding-status';
import { format, parseISO } from 'date-fns';

interface Props {
  timelineEvents: WeddingEventData[];
  unifiedEvents: UnifiedTimelineEvent[];
  unifiedTasks: TimelineTask[];
  unifiedVendorBookings: TimelineVendorBooking[];
  parentEventId: string;
  weddingDate: string;
  eventSlug?: string;
}

type ViewMode = 'unified' | 'events-only';

export function TimelinePageClient({
  timelineEvents,
  unifiedEvents,
  unifiedTasks,
  unifiedVendorBookings,
  parentEventId,
  weddingDate,
  eventSlug,
}: Props) {
  const [viewMode, setViewMode] = useState<ViewMode>('unified');
  const [showShareModal, setShowShareModal] = useState(false);
  const [copied, setCopied] = useState(false);
  const printRef = useRef<HTMLDivElement>(null);

  const shareUrl = eventSlug
    ? `${typeof window !== 'undefined' ? window.location.origin : ''}/share/timeline/${eventSlug}`
    : null;

  const handleCopyLink = () => {
    if (shareUrl) {
      navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const handleExportPDF = () => {
    const eventsByDate = unifiedEvents.reduce((acc, event) => {
      const date = format(parseISO(event.start_datetime), 'yyyy-MM-dd');
      if (!acc[date]) acc[date] = [];
      acc[date].push(event);
      return acc;
    }, {} as Record<string, UnifiedTimelineEvent[]>);

    const sortedDates = Object.keys(eventsByDate).sort();

    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>Wedding Timeline</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: system-ui, -apple-system, sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; }
          h1 { font-size: 28px; color: #be123c; margin-bottom: 8px; }
          .subtitle { color: #666; margin-bottom: 32px; font-size: 14px; }
          .date-header { background: #fef2f2; padding: 12px 16px; margin: 24px 0 12px; border-left: 4px solid #be123c; font-weight: 600; }
          .event { padding: 16px; margin-bottom: 8px; border: 1px solid #e5e7eb; border-radius: 8px; }
          .event-name { font-size: 16px; font-weight: 600; margin-bottom: 4px; }
          .event-time { color: #be123c; font-size: 14px; font-weight: 500; }
          .event-venue { color: #666; font-size: 13px; margin-top: 4px; }
          .event-guests { color: #666; font-size: 13px; }
          .footer { margin-top: 48px; text-align: center; color: #999; font-size: 12px; border-top: 1px solid #eee; padding-top: 24px; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <h1>Wedding Timeline</h1>
        <p class="subtitle">Wedding Date: ${weddingDate ? format(parseISO(weddingDate), 'EEEE, MMMM d, yyyy') : 'TBD'}</p>
        ${sortedDates.map(date => `
          <div class="date-header">${format(parseISO(date), 'EEEE, MMMM d, yyyy')}</div>
          ${eventsByDate[date].map(event => `
            <div class="event">
              <div class="event-name">${event.custom_event_name || event.event_name.replace(/_/g, ' ')}</div>
              <div class="event-time">${format(parseISO(event.start_datetime), 'h:mm a')}${event.end_datetime ? ' – ' + format(parseISO(event.end_datetime), 'h:mm a') : ''}</div>
              ${event.venue_name ? `<div class="event-venue">📍 ${event.venue_name}</div>` : ''}
              ${event.expected_guest_count ? `<div class="event-guests">👥 ~${event.expected_guest_count} guests expected</div>` : ''}
            </div>
          `).join('')}
        `).join('')}
        <div class="footer">Generated by EventKaro • ${format(new Date(), 'MMM d, yyyy')}</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-gray-900">Events & Timeline</h1>
          <p className="text-gray-600 mt-1">
            Manage all your wedding events, tasks, and vendor payments
          </p>
        </div>
        <div className="flex items-center gap-3">
          <button
            onClick={handleExportPDF}
            className="inline-flex items-center gap-2 px-4 py-2 border-2 border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium transition-colors"
          >
            <FileDown className="h-4 w-4" />
            <span className="hidden sm:inline">Export PDF</span>
          </button>
          {eventSlug && (
            <button
              onClick={() => setShowShareModal(true)}
              className="inline-flex items-center gap-2 px-4 py-2 border-2 border-gray-300 text-gray-700 rounded-lg hover:bg-gray-50 font-medium transition-colors"
            >
              <Share2 className="h-4 w-4" />
              <span className="hidden sm:inline">Share</span>
            </button>
          )}
          <Link
            href={`/events/${parentEventId}/setup-timeline`}
            className="inline-flex items-center gap-2 px-4 py-2 bg-rose-700 text-white rounded-lg hover:bg-rose-800 font-medium transition-colors"
          >
            <Plus className="h-4 w-4" />
            <span className="hidden sm:inline">Add Event</span>
            <span className="sm:hidden">Add</span>
          </Link>
        </div>
      </div>

      {/* View Mode Toggle */}
      <div className="flex items-center gap-2 p-1 bg-gray-100 rounded-lg w-fit">
        <button
          onClick={() => setViewMode('unified')}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all ${
            viewMode === 'unified'
              ? 'bg-white text-rose-700 shadow-sm'
              : 'text-gray-600 hover:text-gray-900'
          }`}
        >
          <LayoutGrid className="h-4 w-4" />
          <span className="hidden sm:inline">All Items</span>
          <span className="sm:hidden">All</span>
        </button>
        <button
          onClick={() => setViewMode('events-only')}
          className={`flex items-center gap-2 px-4 py-2 rounded-lg font-medium transition-all ${
            viewMode === 'events-only'
              ? 'bg-white text-rose-700 shadow-sm'
              : 'text-gray-600 hover:text-gray-900'
          }`}
        >
          <Calendar className="h-4 w-4" />
          <span className="hidden sm:inline">Events Only</span>
          <span className="sm:hidden">Events</span>
        </button>
      </div>

      {/* Content */}
      {viewMode === 'unified' ? (
        <UnifiedTimeline
          events={unifiedEvents}
          tasks={unifiedTasks}
          vendorBookings={unifiedVendorBookings}
          parentEventId={parentEventId}
        />
      ) : (
        <TimelineView
          events={timelineEvents}
          parentEventId={parentEventId}
          weddingDate={weddingDate}
        />
      )}

      {/* Share Modal */}
      {showShareModal && shareUrl && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl max-w-md w-full p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="text-lg font-semibold text-gray-900">Share Timeline</h3>
              <button
                onClick={() => setShowShareModal(false)}
                className="p-1 hover:bg-gray-100 rounded-lg"
              >
                <span className="sr-only">Close</span>
                <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                </svg>
              </button>
            </div>
            <p className="text-sm text-gray-600 mb-4">
              Share this link with vendors, family, or guests to let them view the event schedule.
            </p>
            <div className="flex items-center gap-2 bg-gray-50 rounded-lg p-3">
              <input
                type="text"
                readOnly
                value={shareUrl}
                className="flex-1 bg-transparent text-sm text-gray-700 outline-none"
              />
              <button
                onClick={handleCopyLink}
                className={`p-2 rounded-lg transition-colors ${
                  copied ? 'bg-green-100 text-green-700' : 'hover:bg-gray-200 text-gray-600'
                }`}
              >
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
              </button>
            </div>
            {copied && (
              <p className="text-sm text-green-600 mt-2">Link copied to clipboard!</p>
            )}
            <div className="mt-4 pt-4 border-t border-gray-200">
              <p className="text-xs text-gray-500">
                Anyone with this link can view the event schedule. No login required.
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
